version: '3'

volumes:
  data-volume:

services:

  app:
    build: ./app
    working_dir: /home/app/src
    command: yarn start
    depends_on:
      - mongo

  mongo:
    image: "mongo:4"
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db