version: '3'
services:

  web:
    build: .
    working_dir: /home/app/src
    command: yarn start
    ports:
     - "5000:5000"
    depends_on:
      - mongo

  mongo:
    image: "mongo:4"
    ports:
      - "27017:27017"
    volumes:
      - ./data:/home/app/data