version: '3'

volumes:
  data-volume:

services:

  app:
    build: ./app
    working_dir: /home/app
    command: yarn start
    depends_on:
      - mongo

  mongo:
    build: ./mongo
    volumes:
      - data-volume:/data/db