version: '3'

volumes:
  certbot-conf:
  certbot-www:

services:

  app:
    environment:
      - APP_PORT=8080
    expose:
      - 8080

  mongo:
    expose:
      - 27017

  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  admin:
    command: yarn start
    expose:
      - 3000