version: '3'
services:

  web:
    ports:
      - "80:5000"

  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      
  certbot:
    image: certbot/certbot